name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test on ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Babashka
      uses: turtlequeue/setup-babashka@v1.3.0
      with:
        babashka-version: 1.3.176
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Node dependencies
      run: npm ci
      
    - name: Lint Clojure code
      run: |
        # Install clj-kondo
        curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
        chmod +x install-clj-kondo
        ./install-clj-kondo --dir bin
        bin/clj-kondo --lint src test --config .clj-kondo/config.edn
        
    - name: Run Clojure tests
      run: bb test
      
    - name: Build ClojureScript
      run: npm run build:prod
      
    - name: Run ClojureScript tests
      run: npm run test
      
    - name: Build BBPad executable
      run: bb build
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.os }}
        path: |
          target/test-results/
          playwright-report/

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            executable: bbpad
          - os: windows-latest  
            platform: windows
            executable: bbpad.exe
          - os: macos-latest
            platform: macos
            executable: bbpad
            
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Babashka
      uses: turtlequeue/setup-babashka@v1.3.0
      with:
        babashka-version: 1.3.176
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build production assets
      run: npm run build:prod
      
    - name: Create release build
      run: bb release
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bbpad-${{ matrix.platform }}
        path: |
          target/bbpad*
          target/*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'Release v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: BBPad v${{ github.run_number }}
        draft: false
        prerelease: false
        body: |
          ## BBPad Release v${{ github.run_number }}
          
          ### Changes
          - Auto-generated release from CI
          
          ### Downloads
          - **Windows**: bbpad.exe
          - **macOS**: bbpad (Universal Binary)  
          - **Linux**: bbpad (Static Binary)
          
          ### Installation
          1. Download the executable for your platform
          2. Make executable (chmod +x on Unix systems)
          3. Run directly - no installation required!
          
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bbpad-windows/bbpad.exe
        asset_name: bbpad.exe
        asset_content_type: application/octet-stream