name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Babashka
      uses: turtlequeue/setup-babashka@v1.5.0
      with:
        babashka-version: 1.3.176

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Node dependencies
      run: npm ci

    - name: Lint Clojure code
      run: |
        # Install clj-kondo
        curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
        chmod +x install-clj-kondo
        ./install-clj-kondo --dir bin
        bin/clj-kondo --lint src --config .clj-kondo/config.edn

    - name: Run Clojure tests
      run: bb test

    - name: Build frontend
      run: npm run build

    - name: Run frontend tests
      run: npm run test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}
        path: |
          target/test-results/
          bbpad-ui/dist/

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            artifact: bbpad-linux
          - os: windows-latest
            platform: windows
            artifact: bbpad-windows
          - os: macos-latest
            platform: macos
            artifact: bbpad-macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Babashka
      uses: turtlequeue/setup-babashka@v1.5.0
      with:
        babashka-version: 1.3.176

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build production assets
      run: npm run build

    - name: Build Electron app (Linux)
      if: matrix.platform == 'linux'
      run: |
        npx electron-builder --linux --publish=never

    - name: Build Electron app (Windows)
      if: matrix.platform == 'windows'
      run: |
        npx electron-builder --windows --publish=never

    - name: Build Electron app (macOS)
      if: matrix.platform == 'macos'
      run: |
        npx electron-builder --macos --publish=never

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: |
          dist/
          bbpad-ui/dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'Release v')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: BBPad v${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          bbpad-windows/**/*
          bbpad-linux/**/*
          bbpad-macos/**/*
        body: |
          ## BBPad Release v${{ github.run_number }}

          ### Changes
          - Auto-generated release from CI

          ### Downloads
          - **Windows**: Download from bbpad-windows artifacts
          - **macOS**: Download from bbpad-macos artifacts
          - **Linux**: Download from bbpad-linux artifacts

          ### Installation
          1. Download the installer/executable for your platform
          2. Run the installer or make executable (chmod +x on Unix systems)
          3. Launch BBPad!